### ISSUE TITLE
部署node server后无响应

### ISSUE THREAD

**Issue by superexboom** [lkeme/bilibili-pcheartbeat#1]
环境：
Centos7 x64
Nodejs:14.6.0
当前npm list：
bilibili-pcheartbeat@0.0.1 /root/bilibili-pcheartbeat
├─┬ body-parser@1.19.0
│ ├── bytes@3.1.0
│ ├── content-type@1.0.4
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── depd@1.1.2
│ ├─┬ http-errors@1.7.2
│ │ ├── depd@1.1.2 deduped
│ │ ├── inherits@2.0.3
│ │ ├── setprototypeof@1.1.1 deduped
│ │ ├── statuses@1.5.0 deduped
│ │ └── toidentifier@1.0.0
│ ├─┬ iconv-lite@0.4.24
│ │ └── safer-buffer@2.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.7.0
│ ├─┬ raw-body@2.4.0
│ │ ├── bytes@3.1.0 deduped
│ │ ├── http-errors@1.7.2 deduped
│ │ ├── iconv-lite@0.4.24 deduped
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.18
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.27
│     └── mime-db@1.44.0
├─┬ express@4.17.1
│ ├─┬ accepts@1.3.7
│ │ ├── mime-types@2.1.27 deduped
│ │ └── negotiator@0.6.2
│ ├── array-flatten@1.1.1
│ ├── body-parser@1.19.0 deduped
│ ├─┬ content-disposition@0.5.3
│ │ └── safe-buffer@5.1.2 deduped
│ ├── content-type@1.0.4 deduped
│ ├── cookie@0.4.0
│ ├── cookie-signature@1.0.6
│ ├── debug@2.6.9 deduped
│ ├── depd@1.1.2 deduped
│ ├── encodeurl@1.0.2
│ ├── escape-html@1.0.3
│ ├── etag@1.8.1
│ ├─┬ finalhandler@1.1.2
│ │ ├── debug@2.6.9 deduped
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── parseurl@1.3.3 deduped
│ │ ├── statuses@1.5.0 deduped
│ │ └── unpipe@1.0.0 deduped
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── on-finished@2.3.0 deduped
│ ├── parseurl@1.3.3
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@2.0.6
│ │ ├── forwarded@0.1.2
│ │ └── ipaddr.js@1.9.1
│ ├── qs@6.7.0 deduped
│ ├── range-parser@1.2.1
│ ├── safe-buffer@5.1.2
│ ├─┬ send@0.17.1
│ │ ├── debug@2.6.9 deduped
│ │ ├── depd@1.1.2 deduped
│ │ ├── destroy@1.0.4
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── etag@1.8.1 deduped
│ │ ├── fresh@0.5.2 deduped
│ │ ├── http-errors@1.7.2 deduped
│ │ ├── mime@1.6.0
│ │ ├── ms@2.1.1
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── range-parser@1.2.1 deduped
│ │ └── statuses@1.5.0 deduped
│ ├─┬ serve-static@1.14.1
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── parseurl@1.3.3 deduped
│ │ └── send@0.17.1 deduped
│ ├── setprototypeof@1.1.1
│ ├── statuses@1.5.0
│ ├── type-is@1.6.18 deduped
│ ├── utils-merge@1.0.1
│ └── vary@1.1.2
├── fs@0.0.1-security
├─┬ jsdom@16.3.0
│ ├── abab@2.0.3
│ ├── acorn@7.3.1
│ ├─┬ acorn-globals@6.0.0
│ │ ├── acorn@7.3.1 deduped
│ │ └── acorn-walk@7.2.0
│ ├── cssom@0.4.4
│ ├─┬ cssstyle@2.3.0
│ │ └── cssom@0.3.8
│ ├─┬ data-urls@2.0.0
│ │ ├── abab@2.0.3 deduped
│ │ ├── whatwg-mimetype@2.3.0 deduped
│ │ └── whatwg-url@8.1.0 deduped
│ ├── decimal.js@10.2.0
│ ├─┬ domexception@2.0.1
│ │ └── webidl-conversions@5.0.0
│ ├─┬ escodegen@1.14.3
│ │ ├── esprima@4.0.1
│ │ ├── estraverse@4.3.0
│ │ ├── esutils@2.0.3
│ │ ├─┬ optionator@0.8.3
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@2.0.6
│ │ │ ├─┬ levn@0.3.0
│ │ │ │ ├── prelude-ls@1.1.2 deduped
│ │ │ │ └── type-check@0.3.2 deduped
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├─┬ type-check@0.3.2
│ │ │ │ └── prelude-ls@1.1.2 deduped
│ │ │ └── word-wrap@1.2.3
│ │ └── source-map@0.6.1
│ ├─┬ html-encoding-sniffer@2.0.1
│ │ └── whatwg-encoding@1.0.5 deduped
│ ├── is-potential-custom-element-name@1.0.0
│ ├── nwsapi@2.2.0
│ ├── parse5@5.1.1
│ ├─┬ request@2.88.2
│ │ ├── aws-sign2@0.7.0
│ │ ├── aws4@1.10.0
│ │ ├── caseless@0.12.0
│ │ ├─┬ combined-stream@1.0.8
│ │ │ └── delayed-stream@1.0.0
│ │ ├── extend@3.0.2
│ │ ├── forever-agent@0.6.1
│ │ ├─┬ form-data@2.3.3
│ │ │ ├── asynckit@0.4.0
│ │ │ ├── combined-stream@1.0.8 deduped
│ │ │ └── mime-types@2.1.27 deduped
│ │ ├─┬ har-validator@5.1.3
│ │ │ ├─┬ ajv@6.12.3
│ │ │ │ ├── fast-deep-equal@3.1.3
│ │ │ │ ├── fast-json-stable-stringify@2.1.0
│ │ │ │ ├── json-schema-traverse@0.4.1
│ │ │ │ └─┬ uri-js@4.2.2
│ │ │ │   └── punycode@2.1.1 deduped
│ │ │ └── har-schema@2.0.0
│ │ ├─┬ http-signature@1.2.0
│ │ │ ├── assert-plus@1.0.0
│ │ │ ├─┬ jsprim@1.4.1
│ │ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ │ ├── extsprintf@1.3.0
│ │ │ │ ├── json-schema@0.2.3
│ │ │ │ └─┬ verror@1.10.0
│ │ │ │   ├── assert-plus@1.0.0 deduped
│ │ │ │   ├── core-util-is@1.0.2
│ │ │ │   └── extsprintf@1.3.0 deduped
│ │ │ └─┬ sshpk@1.16.1
│ │ │   ├─┬ asn1@0.2.4
│ │ │   │ └── safer-buffer@2.1.2 deduped
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├─┬ bcrypt-pbkdf@1.0.2
│ │ │   │ └── tweetnacl@0.14.5 deduped
│ │ │   ├─┬ dashdash@1.14.1
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├─┬ ecc-jsbn@0.1.2
│ │ │   │ ├── jsbn@0.1.1 deduped
│ │ │   │ └── safer-buffer@2.1.2 deduped
│ │ │   ├─┬ getpass@0.1.7
│ │ │   │ └── assert-plus@1.0.0 deduped
│ │ │   ├── jsbn@0.1.1
│ │ │   ├── safer-buffer@2.1.2 deduped
│ │ │   └── tweetnacl@0.14.5
│ │ ├── is-typedarray@1.0.0
│ │ ├── isstream@0.1.2
│ │ ├── json-stringify-safe@5.0.1
│ │ ├── mime-types@2.1.27 deduped
│ │ ├── oauth-sign@0.9.0
│ │ ├── performance-now@2.1.0
│ │ ├── qs@6.5.2
│ │ ├── safe-buffer@5.1.2 deduped
│ │ ├─┬ tough-cookie@2.5.0
│ │ │ ├── psl@1.8.0 deduped
│ │ │ └── punycode@2.1.1 deduped
│ │ ├─┬ tunnel-agent@0.6.0
│ │ │ └── safe-buffer@5.1.2 deduped
│ │ └── uuid@3.4.0
│ ├─┬ request-promise-native@1.0.9
│ │ ├─┬ request-promise-core@1.1.4
│ │ │ └── lodash@4.17.19
│ │ ├── stealthy-require@1.1.1
│ │ └─┬ tough-cookie@2.5.0
│ │   ├── psl@1.8.0 deduped
│ │   └── punycode@2.1.1 deduped
│ ├─┬ saxes@5.0.1
│ │ └── xmlchars@2.2.0
│ ├── symbol-tree@3.2.4
│ ├─┬ tough-cookie@3.0.1
│ │ ├── ip-regex@2.1.0
│ │ ├── psl@1.8.0
│ │ └── punycode@2.1.1
│ ├─┬ w3c-hr-time@1.0.2
│ │ └── browser-process-hrtime@1.0.0
│ ├─┬ w3c-xmlserializer@2.0.0
│ │ └── xml-name-validator@3.0.0 deduped
│ ├── webidl-conversions@6.1.0
│ ├─┬ whatwg-encoding@1.0.5
│ │ └── iconv-lite@0.4.24 deduped
│ ├── whatwg-mimetype@2.3.0
│ ├─┬ whatwg-url@8.1.0
│ │ ├── lodash.sortby@4.7.0
│ │ ├─┬ tr46@2.0.2
│ │ │ └── punycode@2.1.1 deduped
│ │ └── webidl-conversions@5.0.0
│ ├── ws@7.3.1
│ └── xml-name-validator@3.0.0
└─┬ path@0.12.7
  ├── process@0.11.10
  └─┬ util@0.10.4
    └── inherits@2.0.3 deduped
（github这边是不是没有折叠功能 要是有的话 麻烦提一下 我后续把这部分折叠下）
也如标题所说 部署之后 仅提示server now listening at port 3000
后续无任何反应 并且卡住 但可ctrl c取消
当前配合此脚本一并使用https://github.com/Dawnnnnnn/bilibili-live-tools

**Comment by lkeme** [comment]
不发包肯定没反应，先用`example.py`的`generate_s_test`测试下发包。

**Comment by superexboom** [comment]
已编辑
是之前的代理的后遗症
